field: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
fieldLayouts:
  84cb4dd8-7ce4-4bd8-bf74-5b81b5354995:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: db33cf09-8ba1-45f6-9cc0-3e855cbcb809 # Template
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c521ab82-40b0-45c1-bc2a-14acb42fab5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 605e973b-b2e9-4421-9f1a-80d4cddc0cf0 # Parameter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68d74649-9098-4dc8-8c47-901bb525658a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03deb3d2-8f87-45f0-9002-ee9426351f3d
        userCondition: null
fields:
  605e973b-b2e9-4421-9f1a-80d4cddc0cf0: # Parameter
    columnSuffix: wjuxwjsu
    contentColumnType: text
    fieldGroup: null
    handle: parameter
    instructions: 'Parameters in JSON-Format that will be available to the template'
    name: Parameter
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  db33cf09-8ba1-45f6-9cc0-3e855cbcb809: # Template
    columnSuffix: paidlzyc
    contentColumnType: string
    fieldGroup: null
    handle: template
    instructions: 'Project specific template. Refer to your docs for possible values.'
    name: Template
    searchable: false
    settings:
      includeDirectory: _blocks/dynamic
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\IncludeField
handle: dynamicBlock
name: Dynamic
sortOrder: 8
