field: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
fieldLayouts:
  b0007b65-3686-47ff-a53d-d69c8429ab22:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f7250ac7-93b5-4533-a000-82b9bec48075 # __blank__
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8103001e-3a66-412c-8231-554a6749ec11
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 36a06db2-a9d8-4797-8afc-757369982b57
        userCondition: null
fields:
  f7250ac7-93b5-4533-a000-82b9bec48075: # __blank__
    columnSuffix: kjzpxxkx
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: __blank__
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: 956fbff8-1bb5-4c5d-8e58-ec36d77bf04e # Custom
      columnType: text
      defaultTransform: null
      purifierConfig: Custom.json
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: language
    type: craft\ckeditor\Field
handle: richText
name: 'Rich Text'
sortOrder: 3
