fieldLayouts:
  674b3078-0b6e-4166-8b6d-fa2a29979cd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'The text shown on the cookie banner'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9cf6e525-4440-47ad-a2d9-5b46f85635c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 710a1bd0-9eeb-4721-9493-f2d7dead49ee # Body
            instructions: 'The text shown in the info popup'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef06a53b-0980-424d-9111-8d79fe767056
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 84252758-c1ac-4b17-9042-f669ef34a75e
        userCondition: null
handle: cookieConsent
hasTitleField: true
name: 'Cookie Consent'
section: abd279ac-58c4-41dc-ac32-d2e388e34252 # Legal
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
