fieldLayouts:
  64083172-6049-4f63-a521-593e6ddbf213:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eaebfa07-9439-417d-bf82-7e9898e3b2f4
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a4d9f147-20e7-4db5-9154-194add4298d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98d54ade-ee33-4114-b174-2aadb0fc3234
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 590558bc-36d2-438e-b5f9-ca47506c829d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36c12736-a522-4c35-84ec-5023c1360409
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a8d6836-53b0-4def-bee6-b774cc87918f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # SEO Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81d79fb2-b23f-4c0a-93e4-80ae0298ae5b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d3c7aa2e-b2d2-40ce-aea3-401d0585f6ea
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5042338b-5f7b-4535-96bb-578a829e987c # Topic
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
