fieldLayouts:
  aee8b4ab-cda8-4a5f-a7a3-f3efcc1d74be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            instructions: 'Above the title'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0e37d1a-5d23-4756-a738-3400c2f373fc
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Hero Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 96ef4529-1abd-4c5c-9487-44ff965f7611
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80fa81e4-1f78-4d88-b733-f565d1f5b9bd # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9160991b-cdd7-44e5-9fa0-10d6f3bd48a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 710a1bd0-9eeb-4721-9493-f2d7dead49ee # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 388ca375-23d5-4726-8808-ffedb9297ac7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: CTA
            type: craft\fieldlayoutelements\Heading
            uid: e46dd8dc-23df-436d-8254-fb77a656369a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 08f7545c-870e-4727-a418-660af19052ea # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cd30983-5d8a-4c19-8d71-61e410aa5ff3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Layout
            type: craft\fieldlayoutelements\Heading
            uid: b5509a70-3403-4dd3-a8db-77f6adecd776
            userCondition: null
          -
            elementCondition: null
            fieldUid: 655243f7-46a2-42c0-8de4-188017c31d53 # Hero Area Template
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f384736a-6635-4904-a48d-5d10367a48cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f404ecd-d5b1-42b3-a674-5d6a0745c5f5
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 27127353-b8d1-4c07-a2af-7a273ad8f1f6 # Hero Area
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
