fieldLayouts:
  990b01ed-53fa-475d-a496-910b85940b4c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58725d83-3903-4300-9f2f-5654fea3ba13
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a60cca6a-1b05-4fe3-b17f-6763c3bb8af1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 710a1bd0-9eeb-4721-9493-f2d7dead49ee # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce853bfb-7544-4b83-8daf-6f7fb8769f3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 10ed7f90-b5ae-414d-a27e-ce0c2e680d27 # Features
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 695a3d4a-4c5a-4898-948c-5b5f093ddd21
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01241459-b612-4f2f-972b-31212a86a37a
        userCondition: null
handle: features
hasTitleField: true
name: Features
section: 4d41f740-b1a9-477c-8522-85cf52b2652f # Features
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
