fieldLayouts:
  abb6af40-643c-4b9f-a7ed-d870057e097e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1cabf280-a4f0-4bf9-ae64-cb378e5dd322
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 710a1bd0-9eeb-4721-9493-f2d7dead49ee # Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9b830ec-d6fb-4b95-bfbc-c9be0445ecd5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80fa81e4-1f78-4d88-b733-f565d1f5b9bd # Image
            instructions: 'If blank, the persons photo will be used'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84122edb-e8f7-4438-870b-3b523a7f813e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 33518692-b4a6-4ac6-9423-5631e47f87a5 # Align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4b1a020-15de-485f-b10e-72a71d2241bc
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6bc951bf-74b3-4218-b3aa-dc427967abe9 # Person
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03e9c01e-be7c-4dc7-9b29-c4cbc7a89862
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 85d8d615-699b-4caf-9f98-8911cb602644
        userCondition: null
handle: largeAvatar
hasTitleField: false
name: 'With Large Avatar'
section: db16c9e5-2cfe-4821-88ff-7b18648846a1 # Testimonial
sortOrder: 2
titleFormat: '{body[:50]} - {person.one.title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
