fieldLayouts:
  78605b6a-aeb7-4aa5-b1b6-00c3ab01fa3e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: defc73e4-b96a-4c79-bcab-936391f0bc2b
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 6cd25639-c781-44e3-b74a-d82e6a45e5ec # Show Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b752ae9-a397-4563-98ef-9d978887869e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 710a1bd0-9eeb-4721-9493-f2d7dead49ee # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5aed744c-c447-4bcf-8126-728b32a8930a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7624a4ed-026d-45c4-9431-6fb52daac8b0
        userCondition: null
handle: privacy
hasTitleField: true
name: Privacy
section: abd279ac-58c4-41dc-ac32-d2e388e34252 # Legal
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
