fieldLayouts:
  9e769ade-981f-4d62-8a34-a99331cadaaa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'This entry defines global settings for the entire site.'
            type: craft\fieldlayoutelements\Tip
            uid: f9a8ab04-fba7-4fac-b977-274aa9c15ed4
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: 'As used in the front end'
            label: 'Site Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b9e87b55-ef6f-421f-b975-d74962ec607e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb6b24cc-83d7-416f-be4b-d002c7688b58 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29d387be-3278-42fc-a9d2-2fd1e9a23c71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ebe8548f-7f01-49b6-af98-56da49668e79 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9700ff7-ea01-4a92-a652-11516d38aee1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            instructions: null
            label: 'Default Featured Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd840675-51c0-41da-ab17-eba26aad36d7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b6f55c4a-511b-4037-8d75-358f4bc1ba4f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 370cbaec-9bf1-4ecf-b903-276c6da6c861 # Postal Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d9cf86d-66cf-4e6c-8d8f-ffa9e5dcf475
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bc24da9-fd88-45ec-8410-bc189032e3f8 # Phone Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b921a404-e21a-4930-a0c4-d9ad9da5e1c3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bbe2ff0f-6056-4848-80de-3070bb80294d # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afc3147d-9f54-4d55-80a1-eac004f83b9e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bf3d514d-a34d-41d6-bb20-61c6d8119820 # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d312e13-bf8f-44fb-a9e7-002b366c9eaa
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Info'
        uid: 73e483b6-dbd7-4378-9ce8-e0e6f90046da
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 621ad41b-f019-4e95-96aa-49f8c56482db # SEO Descriction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faf46b13-13e0-4d49-8f58-4c843e7a37b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1dd83a1-2011-4bef-aa20-b6d6a366d66e # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f3c968f-473a-4817-8922-66363870d294
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4733ec62-0324-4ca3-867d-0f59b8c54754
        userCondition: null
handle: siteInfo
hasTitleField: true
name: 'Site Info'
section: 71c1782e-c5bc-4d87-840e-0a4c1a643eff # Site Info
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
