fieldLayouts:
  16071f75-24f5-4201-950a-92a09401de15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09d5eb95-8f04-4cb6-bd16-0d2d58bf14a5
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 10617d77-96d5-4e35-a350-350fb771f91c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: b7e84646-2ab1-476a-97a1-49ac1fa05852 # Is Featured
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 382b6359-fa1d-46e4-9203-eed226f4abec
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 734e1cb2-3bcc-4970-81e7-5a2999f2e191
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee886fff-a72a-4a22-b217-f878c7f53ffe # Persons
            instructions: null
            label: Authors
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83eae09d-e203-4827-acc3-a029af6fd9ff
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 05ab0680-2ccc-4a59-932a-07311f773d42 # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f699022-9085-4a00-b9e8-b85bf00d7035
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a9758a6-8c25-4c57-a28a-57ee18188fc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 44993cef-3718-479f-8c88-bdede1d256ba # Card Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b337f51-9f5b-4a0e-9b2c-a3f49c8cc727
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12ee7163-1896-4afc-b140-3f53c59f8b7d # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60eaceea-a6ce-4fa9-899d-e323a80cac16
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 340c3b24-7f05-4789-b077-a502b4310109 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4452f89d-cd34-4898-9449-c9929305d727
            userCondition: null
            warning: null
            width: 25
        name: Data
        uid: 04857412-02c9-4c1f-bb50-56b63fe32a8b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c0fe6eff-5323-415f-81d9-4f9d42a07b66 # Story Content
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bee8737-9e26-48b4-ad38-43ad7c662162
            userCondition: null
            warning: null
            width: 100
        name: Story
        uid: f94e030f-1f1c-4656-abd4-ad5a1062daa6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7ef9424e-9902-4930-9244-8d7f93d6dc4b # Story Team
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 270417c5-e78b-4843-bf9a-05185f85d764
            userCondition: null
            warning: null
            width: 100
        name: Team
        uid: e32a2642-268f-4a5f-9e90-dfb8c2fe2222
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # SEO Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f2c725b-9d7a-4c25-bccb-329544c6aa22
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2d62d4a1-d729-4b4c-b740-3b2e3639617a
        userCondition: null
handle: story
hasTitleField: true
name: Story
section: 2f93cb45-a9ce-4284-8848-9eb001fb8a1c # Article
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
