fieldLayouts:
  e463be1c-a88a-40f9-9d31-e772cc9690ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0767f000-e433-4930-9534-b795a48740bb # Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48681c9a-24c8-4695-b31e-b58218980afb
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 559dda1e-9a33-4857-aaf3-ac1bcce65160
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80fa81e4-1f78-4d88-b733-f565d1f5b9bd # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64580eeb-e575-4374-9ba3-0e7fa0745a9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95083646-e6d9-4b6d-baf6-bc5e14f86c58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 79e20dfb-3edc-467c-a1e9-826c362d54b6
        userCondition: null
handle: twoColumnsWithImage
hasTitleField: true
name: 'Two columns with image'
section: 07fce1cd-37fc-4742-acf8-6bc0a4efd7d7 # Two Columns With Image
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
