headingLevels: false
name: Table
options:
  alignment:
    options:
      - left
      - right
      - center
  table:
    contentToolbar:
      - tableColumn
      - tableRow
      - mergeTableCells
toolbar:
  - insertTable
  - '|'
  - alignment
  - '|'
  - bold
  - italic
  - '|'
  - link
