css: ".ck.ck-content ul, .ck.ck-content ol {\r\n  padding-left: 20px !important;\r\n}"
headingLevels: false
name: Custom
options:
  link:
    decorators:
      isNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        defaultValue: false
        label: 'Open in a new tab'
        mode: manual
  removePlugins:
    - ListProperties
toolbar:
  - bold
  - italic
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - '|'
  - link
