headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Custom
options:
  removePlugins:
    - AutoImage
    - BlockQuote
    - Code
    - CodeBlock
    - Heading
    - HorizontalLine
    - MediaEmbed
    - TodoList
    - Underline
toolbar:
  - bold
  - italic
  - bulletedList
  - link
