columnSuffix: null
contentColumnType: text
fieldGroup: bd76fb6e-8765-41d3-8e8a-02e37e127c80 # Common
handle: cardText
instructions: 'Displayed on index pages instead of the tagline'
name: 'Card Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
