columnSuffix: ukhovnob
contentColumnType: string(120)
fieldGroup: c38953ca-ba84-4992-8deb-65aa2fc40b34 # Hero Area
handle: ctaCaption
instructions: null
name: 'CTA Caption'
searchable: false
settings:
  byteLimit: null
  charLimit: 30
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
