columnSuffix: zpkytjei
contentColumnType: string
fieldGroup: bef1d233-b346-4d06-a2c1-be50cca6eae2 # Content Sections
handle: gridStyle
instructions: null
name: 'Grid Style'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - 'Default (Grid)'
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Columns
        -
          - value
          - columns
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
