columnSuffix: jyzfhgbr
contentColumnType: text
fieldGroup: c38953ca-ba84-4992-8deb-65aa2fc40b34 # Hero Area
handle: heroTagline
instructions: null
name: 'Hero Tagline'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
