columnSuffix: utamlmxc
contentColumnType: text
fieldGroup: b61bea97-e4d4-4de2-9149-15f74906945a # SEO
handle: seoDescriction
instructions: null
name: 'SEO Descriction'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
