columnSuffix: zvkjsfie
contentColumnType: string
fieldGroup: bef1d233-b346-4d06-a2c1-be50cca6eae2 # Content Sections
handle: testimonialStyle
instructions: null
name: 'Testimonial Style'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - 'With overlapping image'
        -
          - value
          - overlappingImage
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'With large avatar'
        -
          - value
          - largeAvatar
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
