columnSuffix: null
contentColumnType: string
fieldGroup: d50026f3-a236-4ae2-b00a-af55076acd17 # Site
handle: textModules
instructions: null
name: 'Text Modules'
searchable: false
settings:
  contentTable: '{{%matrixcontent_textmodules}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
