columnSuffix: kylmvrit
contentColumnType: char(7)
fieldGroup: 669ee208-7bb0-4800-ba43-454bc31751ac # Story
handle: textColor
instructions: null
name: 'Text Color'
searchable: false
settings:
  defaultColor: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
