#!/bin/bash

if [ -z $1 ]
then
    echo Project name missing
    exit 1
fi

echo Installing project $1...

ddev config --project-name=$1
ddev start &&
ddev composer install &&
ddev craft install --interactive=0 --username=admin --password=password --email=admin@example.com &&
ddev craft index-assets/one images &&
echo Installing npm dependencies...
ddev exec npm install &&
ddev exec npm run build &&
ddev describe &&
ddev craft main/init
ddev launch



