#!/bin/bash

if [ -z $1 ]
then
    echo Project name missing
    exit 1
fi

echo Installing project $1...

ddev config --project-name=$1 --project-type=php --php-version=8.1 --http-port=81
ddev start &&
ddev php ./setup/create-environment-file.php $1 &&
ddev composer install --no-dev &&
ddev php craft install --interactive=0 --username=admin --password=password --email=admin@example.com &&
echo Installing npm dependencies...
ddev exec npm install &&
ddev exec npm run build &&
ddev describe &&
echo Add some wide images, cd into $1 and run ddev craft main/init
ddev launch admin



