defaultPlacement: end
enableVersioning: true
handle: features
name: Features
previewTargets:
  -
    __assoc__:
      -
        - label
        - Preview
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/preview
    uriFormat: 'preview/{section.handle}/{slug}'
  dbf50cb2-37c8-45f7-b375-dcb93e09691b: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/preview
    uriFormat: 'preview/{section.handle}/{slug}'
type: channel
