name: craft4-starter
type: craftcms
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.4"
composer_version: "2"
nodejs_version: "18"

# See https://ddev.readthedocs.io/en/stable/users/configuration/config/ for more configuration options.
# See https://ddev.readthedocs.io/en/stable/users/usage/commands/#debug-migrate-database for more information on database migrations.
